name: JPackage

on:
  push:
    branches: [ release/* ]
  workflow_dispatch:

env:
  pkg-name: 'Weylandinator'
  pkg-version: '1.0'

jobs:
  osx:
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '>11.0.3'
        java-package: jdk
  
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: JPackage
      run: ./gradlew jpackage
    
    - name: Upload dmg
      uses: actions/upload-artifact@v1
      with:
        name: Weylandinator-Mac.dmg
        path: "build/jpackage/${{ env.pkg-name }}-${{ env.pkg-version }}.dmg"

    - name: Upload pkg
      uses: actions/upload-artifact@v1
      with:
        name: Weylandinator-Mac.pkg
        path: "build/jpackage/${{ env.pkg-name }}-${{ env.pkg-version }}.pkg"

  windows:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '>11.0.3'
        java-package: jdk
  
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: JPackage
      run: ./gradlew jpackage
    
    - name: Upload msi
      uses: actions/upload-artifact@v1
      with:
        name: Weylandinator-Win.msi
        path: "build/jpackage/${{ env.pkg-name }}-${{ env.pkg-version }}.msi"

    - name: Upload Installer
      uses: actions/upload-artifact@v1
      with:
        name: Weylandinator-Win.exe
        path: "build/jpackage/${{ env.pkg-name }}-${{ env.pkg-version }}.exe"
